### ISSUE TITLE
When clicking on a report row popover opens. Can't be dismisssed

### ISSUE THREAD

**Issue by robbieaverill** [bringyourownideas/silverstripe-maintenance#103]
When you click on a report row it will trigger the "module info" popover to open.

Clicking the report row again will not close it.

It either should, or we could add a "X" close button into the popover, top right maybe.

**Comment by NightJar** [comment]
![image](https://user-images.githubusercontent.com/778003/41131874-ccd21b5c-6b11-11e8-8d30-61f439c02baf.png)

**Comment by ScopeyNZ** [comment]
![image](https://user-images.githubusercontent.com/3260989/41131957-488daf5e-6b12-11e8-890b-15cd03152c56.png)

**Comment by raissanorth** [comment]
Clicking the row when the popover is open first triggers the popover's native closing mechanism, _then_ the click on the row is registered and opens it again; see below for reference 
https://github.com/bringyourownideas/silverstripe-maintenance/blob/4f95fdaca989856479b427ee968a3bd64e0b6b75/client/src/legacy/entwine/SiteSummary.js#L25-L36

**Comment by robbieaverill** [comment]
Oh cool, we need to adjust that logic again 😆

**Comment by robbieaverill** [comment]
I guess in that same logic we could add a data attribute to the row like `data-popover-opened="1"` then check for and remove that when this logic is re-triggered - use that to control whether to auto-click the popover's trigger inside the table row in some cases but not always

**Comment by robbieaverill** [comment]
Fix at #117
