### ISSUE TITLE
Add Transifex configuration for SS4 version

### ISSUE THREAD

**Issue by robbieaverill** [bringyourownideas/silverstripe-maintenance#104]
Add Transifex localisation support for this module.

We're not able to maintain Transifex easily between two versions, so we should do this for SS4 only.

**Comment by robbieaverill** [comment]
Done with https://github.com/bringyourownideas/silverstripe-maintenance/commit/37f6b0e0494b030fa954a728de5bf8254c6b5663 and https://github.com/bringyourownideas/silverstripe-composer-security-checker/commit/676382049f553e40539cfda0d135dbf5dfdccc51

Transifex URLs: https://www.transifex.com/silverstripe/silverstripe-composer-security-checker and https://www.transifex.com/silverstripe/silverstripe-maintenance

@spekulatius the Transifex projects are hosted under silverstripe's account, I've sent you a project maintainer invite to join the team. If you'd rather host it separately that's fine too and I'm sure we can transfer it =)

**Comment by spekulatius** [comment]
Hello @robbieaverill 

thanks for adding this. Are you able to add my account "spekulatius" to the project directly? The email must have got lost in my gmail I guess.

Cheers,
Peter

**Comment by robbieaverill** [comment]
Cool @spekulatius, done

**Comment by spekulatius** [comment]
Awesome, thank you
