### ISSUE TITLE
A default top property is needed for .health_indicator

### ISSUE THREAD

**Issue by NightJar** [bringyourownideas/silverstripe-maintenance#116]
Browsers that aren't Chrome seem to deal with this in interesting manners.
The element is currently positioned absolute with a default `right` property, but no `top` property seems to see browsers do as they please with the alignment.

![image](https://user-images.githubusercontent.com/778003/42068511-773ccb7a-7ba0-11e8-9ada-1b5034ed3d14.png)

Adding a `top: 1.2308rem` to the `a` that is `.health-indicator` sees the issue solved, however this needs to be done appropriately with scss variables - the value here is the `padding-top` from the parent `h3` that is `.pacakge-summary__details-header`

**Comment by robbieaverill** [comment]
Reprodued on Windows 10 with IE11

![image](https://user-images.githubusercontent.com/5170590/42665505-03d7935a-8694-11e8-92d9-da3acb7c3007.png)

**Comment by robbieaverill** [comment]
Fix at #118
