### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by chillu** [bringyourownideas/silverstripe-maintenance#119]
Make it easier for decision makers :)

**Comment by sachajudd** [comment]
It would also be good to add some screenshots to the userguide for the same reasons 🙂 looks a bit empty at the moment when it's pulled into user help: https://userhelp.silverstripe.org/en/4/optional_features/modules_report/

**Comment by brynwhyman** [comment]
This was resolved with https://github.com/bringyourownideas/silverstripe-maintenance/pull/128

A screenshot was also added for the userdocs: https://github.com/bringyourownideas/silverstripe-maintenance/blob/master/docs/en/userguide/index.md
