### ISSUE TITLE
Errors occur trying to write composer caches

### ISSUE THREAD

**Issue by ScopeyNZ** [bringyourownideas/silverstripe-maintenance#121]
This package uses Composer API to get information about packages. When this happens, composer attempts to write caches to the configured cache directory (`.composer`) using the `COMPOSER_HOME` or `HOME` environment variable. This causes errors on CWP where the `.composer` parent directory is not writable (this comes from `HOME`).

We have anticipated this in `bringyourownideas/silverstripe-composer-update-checker`: https://github.com/bringyourownideas/silverstripe-composer-update-checker/blob/1/src/Extensions/ComposerLoaderExtension.php#L100-L112

This code should be migrated to this module.

This causes Greylog to be flooded with errors.

**Comment by ScopeyNZ** [comment]
Raising the priority. I realised that it's quite likely environments have a `HOME` environment variable defined - if this is not writable then the extension code won't resolve the issue. We should probably just rely on `COMPOSER_HOME`, the fallback to `HOME` seems a little unsafe - although usually you would expect `HOME` to be writable...

**Comment by indygriffiths** [comment]
Has there been any movement on this issue? The "permission denied" error from this module and the update checker has chewed through almost half of our monthly Raygun error allocation.

**Comment by robbieaverill** [comment]
@indygriffiths would you like to try the patch on the platform? That's really all that's holding this up

**Comment by robbieaverill** [comment]
See https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/43#pullrequestreview-155382377

**Comment by brynwhyman** [comment]
@indygriffiths have you had a chance to test this patch? If not, I'll get the team to look at it this week. Sorry for the delay on this one.

**Comment by robbieaverill** [comment]
Fixed in #42 and #43
