### ISSUE TITLE
"More info" button is out of alignment with its icon

### ISSUE THREAD

**Issue by robbieaverill** [bringyourownideas/silverstripe-maintenance#124]
**Version: CWP 2.2.x-dev, maintenance 2.1.x-dev, SilverStripe 4.3.x-dev**

![image](https://user-images.githubusercontent.com/5170590/49096467-e3f8f900-f26a-11e8-9cae-e62dae1cbb2b.png)

The text and icon are slightly out of alignment.

May also be affecting the "Explore addons" button:

![image](https://user-images.githubusercontent.com/5170590/49096554-1145a700-f26b-11e8-863f-4be8c9deada9.png)

**Comment by robbieaverill** [comment]
PR at #125

**Comment by ScopeyNZ** [comment]
Fixed in #125
