### ISSUE TITLE
"More info" should point to user docs

### ISSUE THREAD

**Issue by chillu** [bringyourownideas/silverstripe-maintenance#127]
"More info" in this context is user level, it should point to user docs

![image](https://user-images.githubusercontent.com/111025/54639957-790e4f00-4af3-11e9-8be2-34bdd8e3c87b.png)

**Comment by robbieaverill** [comment]
For the latter point, see https://github.com/bringyourownideas/silverstripe-maintenance/issues/110

**Comment by chillu** [comment]
Sweet, removed it from the description :)

**Comment by robbieaverill** [comment]
PR #130
