### ISSUE TITLE
PHP 7.3 compatibility with 1.x branch

### ISSUE THREAD

**Issue by brynwhyman** [bringyourownideas/silverstripe-maintenance#132]
### Background
PHP 7.1 is EOL in Dec 2019. Following this, SilverStripeLtd is planning to provide PHP >=7.2 support for modules compatible with version 3.7.x of the SilverStripe CMS, and 4.x versions based on the [support timeline](https://www.silverstripe.org/software/roadmap/).

### Overview
The 1.x release line of the module is limited to PHP ~7.1.0 and below.

After a quick look, I couldn't find a clear reason for the lock in PHP versions, so raising this issue to track.

**Comment by robbieaverill** [comment]
We originally dropped PHP 7.2 from this branch because Object was renamed to SS_Object. https://github.com/bringyourownideas/silverstripe-maintenance/pull/51

We can re-introduce support for PHP 7.2+ by using the [class renaming shim](https://docs.silverstripe.org/en/3/changelogs/3.7.0/#for-module-authors) instead.

**Comment by robbieaverill** [comment]
Related: https://github.com/bringyourownideas/silverstripe-composer-update-checker/issues/36

**Comment by robbieaverill** [comment]
Assuming this means that CWP 1.9 needs to support PHP 7.2+ I'm going to be making **patch change** pull requests too all modules that need support for this in the cwp-installer. This won't include (initially) any of the optional dependencies. Modules like realme already have issues to update their PHP support (including for SS3).

**Comment by robbieaverill** [comment]
I've changed my mind, it's going to be tidier to release new versions that explicitly require PHP 7.2, and we should release this as CWP 1.10

**Comment by robbieaverill** [comment]
PR at https://github.com/bringyourownideas/silverstripe-maintenance/pull/133
