### ISSUE TITLE
Remove references to security checker as it's now broken

### ISSUE THREAD

**Issue by andrewandante** [bringyourownideas/silverstripe-maintenance#155]
As of https://github.com/bringyourownideas/silverstripe-composer-security-checker/issues/57 the security checker is properly broken, giving me the error:

```sh
$ /var/www/mysite/www$ vendor/bin/sake dev/tasks/SecurityAlertCheckTask
Running Task Composer security checker

ERROR [UNKNOWN TYPE, ERRNO 403]: Uncaught SensioLabs\Security\Exception\HttpException: The web service failed for an unknown reason (HTTP 403).
IN GET dev/tasks/SecurityAlertCheckTask
Line 133 in /var/www/mysite/www/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler.php
```

So it's probably best to remove references to it (or flag them at least) in this repo

**Comment by brynwhyman** [comment]
The module has also been removed from the CMS recipe-reporting-tools which was a common way to bring the module in through the CWP and SS installer: https://github.com/silverstripe/recipe-reporting-tools/issues/16

**Comment by brynwhyman** [comment]
Done in https://github.com/bringyourownideas/silverstripe-maintenance/pull/165
