### ISSUE TITLE
Report not updating on CWP-2.8.0-rc1

### ISSUE THREAD

**Issue by emteknetnz** [bringyourownideas/silverstripe-maintenance#163]
Queued job said that it was 'Running', though nothing happened after several minutes.

Report was showing old data?
Version: CWP 2.7.x-dev, SilverStripe CMS 4.7.x-dev
Last updated Mar 22, 2021 2:53 AM 

CMS 'logo version' on bottom left of CMS was reporting 4.8

Also, not sure if it's related to the the above, even with the old data present, when I filtered on 'CWP recipe module' it showed no results

**Comment by GuySartorelli** [comment]
Is this easily reproducible if you delete the job and try again?
Is there anything in the logs or the job messages that could point at a cause?

**Comment by GuySartorelli** [comment]
No longer an issue
