### ISSUE TITLE
Report shows encoded HTML instead of HTML

### ISSUE THREAD

**Issue by emteknetnz** [bringyourownideas/silverstripe-maintenance#215]
CMS 5 using 3.x-dev

![image](https://github.com/bringyourownideas/silverstripe-maintenance/assets/4809037/6e58b82e-9c90-4cd5-bf19-b6bc8b876221)

**Comment by GuySartorelli** [comment]
This is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/11191
