### ISSUE TITLE
Addons is decommissioned, so CheckForUpdatesJob fails

### ISSUE THREAD

**Issue by elliot-sawyer** [bringyourownideas/silverstripe-maintenance#218]
### Module version(s) affected

3.1.0

### Description

This URL is no longer valid because `The dedicated Addons site has been discontinued`

ModuleHealthLoader::getModuleHealthInfo(), L23: 
`$endpoint = 'addons.silverstripe.org/api/ratings?addons=' . implode(',', $addons);`

### How to reproduce

https://addons.silverstripe.org/api/ratings?addons=bringyourownideas/silverstripe-composer-update-checker,bringyourownideas/silverstripe-maintenance

### Possible Solution

I'm not expecting this would be fixable, unless there's plans to refactor this module to use Packagist instead.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
This was fixed as part of https://github.com/bringyourownideas/silverstripe-maintenance/pull/220 - because of the breadth of the changes it won't be tagged until the next minor release.
