### ISSUE TITLE
Refactor scheduling of queuedjobs

### ISSUE THREAD

**Issue by spekulatius** [bringyourownideas/silverstripe-maintenance#25]

**Comment by robbieaverill** [comment]
This might be useful to cover with #38

**Comment by robbieaverill** [comment]
We've removed the ScheduledJob implementation, so to replace this I propose that we add logic to the CheckForUpdatesJob to reschedule itself after it's finished running. The time difference could be 24 hours by default, and be configurable.

1 point estimate on this basis.

**Comment by robbieaverill** [comment]
Note that this could mess up the "check for updates" button in the report which is looking for pending jobs existing

**Comment by robbieaverill** [comment]
Fixed with https://github.com/bringyourownideas/silverstripe-maintenance/pull/95
