### ISSUE TITLE
Link to module information on Addons

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#32]
As a CMS user
I want to access to user support documentation
So that I can learn how to use the features of a module 

## Acceptance criteria

- A link is available to the module's page on addons.silverstripe.org
- Module provides access to more information (readme/addons link)
- Links to the readme will anchor directly to the top of the readme document

### Nice to haves

- Link to developer docs
- Link to user help documentation if available/ applicable

### Notes

We don't have structured data for user help documentation yet. This may be able to be achieved by adding some metadata to a module's composer.json file to point at it when it exists - we'd need to check if this data would make its way through Packagist and into this module via API before it's worth pursuing.

**Comment by robbieaverill** [comment]
>Link to developer docs

Can this please be clarified? If it's the same thing as the readme, we've already mentioned it a couple of times.

cc @be2n

**Comment by spekulatius** [comment]
Maybe a link to the homepage as defined in the composer.json? Usually its the module at Github.

**Comment by robbieaverill** [comment]
I guess that's the best we can do for now. We can link to the VCS repository too

**Comment by robbieaverill** [comment]
Note for SS3 version:

* Make the table row in the report a link
* The link should go to the module on the addons site
* It should open in a new window
