### ISSUE TITLE
Identify CWP specific modules

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#34]
As the business owner of a CWP site
I want to know what modules are specific to CWP recipes
So that I can identify what modules are supported by SilverStripe and the modules that are not

## Acceptance criteria

- Modules can be sorted by a 'CWP modules' tag, filter, etc, and by non CWP modules
- CWP recipe modules are ID on an unsorted list
- The filter exists in CWP, not in this module (since it's specific to CWP)
- Link out to information on what CWP recipes are (help question mark in SS4)

## Notes

- If SilverStripe 3 provides a GridField component to provide the dropdown with filters as in the designs then implement it, but if it doesn't exist already then don't add it. This could be a SilverStripe 4 only feature.

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by robbieaverill** [comment]
From a backend perspective, I suppose we'll use a "cwp" tag in the composer.json information to find these modules

**Comment by robbieaverill** [comment]
We discussed this just now and decided that using a tag in composer.json is possibly not the best way to achieve this. Raised an issue at https://github.com/silverstripe/addons.silverstripe.org/issues/190 for  further discussion.
