### ISSUE TITLE
Display the current version of SilverStripe and/or CWP

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#35]
As a Product Owner
I want to be able to access the version of SilverStripe CMS and CWP my site uses
So that I can make more informed decisions about product investment

## Acceptance criteria

- The version of the SilverStripe CMS is displayed
- (CWP only) The version of the main CWP recipe used is displayed
  - In both CWP versions, the cwp/cwp-core module (only mandatory requirement) can be used to determine this
- Versions are displayed in the summary section of the report

## Notes

This information is already available by hovering over the SilverStripe logo in the top left corner (may currently be broken for CWP) - the backend for this can be re-used.

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by robbieaverill** [comment]
@ScopeyNZ see @clarkepaul's comment [here](https://github.com/silverstripe/silverstripe-reports/issues/100#issuecomment-391155546): 

>From memory there is a Gridfield header which normally sits under the actions (above gridfield), if true then perhaps the Version details should become the header.

**Comment by clarkepaul** [comment]
Bet me to it :)
