### ISSUE TITLE
Add button to link out to addons.silverstripe.org

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#36]
As a Product Owner
I want to find other modules I can use on my site
So that I can reuse code when possible

## Acceptance criteria

- There is a link out to the add-on site

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by raissanorth** [comment]
@clarkepaul @sachajudd Could you please add the icon(s) from the design to Fontastic, please? I am happy to add it(/them) to the admin repo once that's done. 

![image](https://user-images.githubusercontent.com/14869519/40157388-d9960f0e-59f2-11e8-9f23-e6a8f699ad81.png)

**Comment by clarkepaul** [comment]
This will be a task for @newleeland, he should be able to sort before next week.
