### ISSUE TITLE
Ensure report is available as a CSV export

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#37]
As a Product Owner
I want to be able to generate a report from the Site Summariser
So that I can do further analysis and share the information with a wider group of people

## Acceptance criteria

- .csv export with complete information table is available
- Report data is in human discernable format

**Comment by robbieaverill** [comment]
Woops, wrong issue!

**Comment by NightJar** [comment]
Yes and no, will be resolved by #49
