### ISSUE TITLE
Add "refresh report" button to the interface

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#38]
As a Product Owner
I want to be able to refresh the report when necessary
So that I have up-to-date information

## Acceptance criteria

- Action to manually trigger a new report (generate report button)
- Displays a loading spinner while processing
- Actual generation should be done in the background via a queued job or similar
- Show a date stamp somewhere for when report was last generated

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

An example of this kind of process is the "external links" module which will do some AJAX polling to check whether the backend process has finished yet.

**Comment by newleeland** [comment]
**Potential Checking design** @raissanorth 
https://projects.invisionapp.com/d/main#/console/13434881/298994490/preview

**Comment by robbieaverill** [comment]
@newleeland the link isn't working for me
