### ISSUE TITLE
Show module health as a visual indicator in the list

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#41]
As a Product Owner
I want to know the health of each module
So that I a great understand of my sites technical debt.

## Acceptance criteria

- Module rating is displayed for ~~most recent release~~ default branch only (from addons site)
- Matches designs (circular image indicator and numeric indicator)

## Considerations

- ~~The addons site rating system is currently broken (https://github.com/silverstripe/addons.silverstripe.org/issues/172), and work is nearing completion to replace it with a new system (https://github.com/silverstripe/addons.silverstripe.org/issues/178)~~ done
- ~~The addons site does not have an API to expose the data for this yet so we will need to add one (https://github.com/silverstripe/addons.silverstripe.org/issues/180)~~ done

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by robbieaverill** [comment]
This ticket needs to be re-estimated, since building the API in addons was part of the 8 points. Thoughts @raissanorth @ScopeyNZ @NightJar?
