### ISSUE TITLE
Upgrade module to run on SilverStripe 4.0

### ISSUE THREAD

**Issue by rupachup** [bringyourownideas/silverstripe-maintenance#42]
As part of the development work for "site summariser" we expect to complete the majority of the functionality and development work against the SilverStripe 3.x compatible version, then upgrade everything to work on 4.x at the end.

## Acceptance criteria

- [x] All features of the module work on SilverStripe 4 (PR: #78)
- [x] Designs are updated to match (related: #81)
- [x] When updating the list, there is an indicator that the report is being processed
- [x] Badges are use different colours depending on warning level
- Module info remains under the module name (moving it to a popup will be a separate issue https://github.com/bringyourownideas/silverstripe-maintenance/issues/68)

## Sub tasks

- [x] Update the composer update checker module to SS4
- [x] Update the security checker module to SS4

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by raissanorth** [comment]
This will also require new font icons to be added to the admin module, once they are available on Fontastic.

**Comment by robbieaverill** [comment]
I've moved the SS3 code to the `1` branch, updated the branch aliases for master and `1` and have added the composer, Travis and phpunit requirements for SS4. We need to run the upgrader now and get it working on 4!

**Comment by robbieaverill** [comment]
@ScopeyNZ has done the bulk of the upgrading work in #78, I've converted the remaining AC's into tasks in the description and logged a couple of new issues: #79 #80 #81 that should be done at some point too.

**Comment by robbieaverill** [comment]
Done! Nice work team
