### ISSUE TITLE
SPIKE: Investigate methods for identifying whether a module has been forked

### ISSUE THREAD

**Issue by rupachup** [bringyourownideas/silverstripe-maintenance#43]
As part of the module stability reporting we would ideally like to be able to identify (in some way) modules that have been forked.

For example, if a dev has forked silverstripe/cms then we expect there to be two indicators for this:

* a VCS repository registered in composer.json
* _potentially_ (not necessarily) a non-standard branch or tag

In some cases modules are supposed to be forked - for example the silverstripe/blog module is a fork.

This issue is to investigate how we can achieve the ability to identify modules that a dev has forked (making it unsafe)

* [ ] Raise issue for implementation

**Comment by clarkepaul** [comment]
@robbieaverill this was lurking in the backlog. Is this still relevant for this sprint?

**Comment by robbieaverill** [comment]
It is relevant but I think it was a stretch goal

**Comment by ScopeyNZ** [comment]
To consider: https://developer.github.com/v3/repos/forks/

**Comment by robbieaverill** [comment]
It gets tricky because some of our supported modules are forks themselves

**Comment by GuySartorelli** [comment]
This is unlikely to ever be actioned. If we do prioritise this again in the future we are likely to create a new spike anyway.
