### ISSUE TITLE
Remove report description

### ISSUE THREAD

**Issue by robbieaverill** [bringyourownideas/silverstripe-maintenance#60]
![image](https://user-images.githubusercontent.com/5170590/40342755-8a3b2222-5de0-11e8-837e-1d92dcb691b6.png)

Following up from #31, the description is not part of the designs, so should be removed.

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

**Comment by clarkepaul** [comment]
Are we able to put a direct link to the Maintenance module Readme (in Addons) as per designs by using a (?) icon in SS3.

**Comment by ScopeyNZ** [comment]
I'm not sure that there's a (?) icon available but there is a cursive "i" in a circle?
