### ISSUE TITLE
Add a link to provide more information about Site Summariser module

### ISSUE THREAD

**Issue by clarkepaul** [bringyourownideas/silverstripe-maintenance#61]
Presented as an (i) icon in the design, add a link to the module silverstripe-maintenance within Addons for more information about what the module does.

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

Related but not part of this issue:
Update the module to include details about the three columns https://github.com/bringyourownideas/silverstripe-maintenance/issues/62

**Comment by robbieaverill** [comment]
PR at https://github.com/bringyourownideas/silverstripe-maintenance/pull/86
