### ISSUE TITLE
Update the module readme and docs

### ISSUE THREAD

**Issue by clarkepaul** [bringyourownideas/silverstripe-maintenance#62]
With all the changes to the module (silverstripe-maintenance) we should update the Readme to include any UI updates and how to interpret the functionality it provides.

Examples of what needs mentioning:
* What "Installed, Available, Latest" means
* Security alerts—what the alert means, where to get more info, what does the tag mean eg. erg-345-345

Note: this is going to need to be updated again once we have more module work complete so this issue is to do a first shot at removing anything which is misleading or completely wrong.

**Comment by robbieaverill** [comment]
Ideally this gets done after we're feature complete

**Comment by clarkepaul** [comment]
@robbieaverill  It isn't clear if we will continue development past this sprint, if we bring more items into sprint then we can leave it until the end of the current sprint otherwise it'll just need to be done.

**Comment by robbieaverill** [comment]
Sounds good @clarkepaul

**Comment by robbieaverill** [comment]
Fixed with #106
