### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by spekulatius** [bringyourownideas/silverstripe-maintenance#7]
Currently there aren't any tests :( Some phpunit test would be nice.

**Comment by robbieaverill** [comment]
We're expecting to add tests as we go, so let's close this as soon as some exist and we'll keep adding new ones as we go =)

**Comment by spekulatius** [comment]
Great, thanks for the information :)

**Comment by spekulatius** [comment]
Sounds good to me @robbieaverill. Do you want to open a pull request for this?

**Comment by robbieaverill** [comment]
Yep, initial PR at #44

**Comment by robbieaverill** [comment]
#44 contains the start for this, we'll chip away at it incrementally from here on =)
