### ISSUE TITLE
Remove print button or fix the output of print content

### ISSUE THREAD

**Issue by clarkepaul** [bringyourownideas/silverstripe-maintenance#96]
The print output of the maintenance module needs some tidy up after the fact that we have added a bunch of HTML to the grid items. If we want to keep print functionality we should tidy up the output to resemble otherwise my suggestion is to remove the print action for the time being.

**Comment by robbieaverill** [comment]
Affects SS3 as well:
![image](https://user-images.githubusercontent.com/5170590/41012067-ffa75cba-6993-11e8-8c2c-1d2cf4bc4af3.png)

**Comment by robbieaverill** [comment]
Closing as done in SS3 version, it'll get merged up for SS4 at some point =)

**Comment by sminnee** [comment]
@robbieaverill or @ScopeyNZ could we remove type/enhancement from this?

**Comment by robbieaverill** [comment]
Done
